#!/bin/bash
# Git commands to stage and commit the new modern theme

echo "🔍 Checking git status..."
git status

echo ""
echo "📝 New files created:"
echo "  - assets/css/main.scss (main stylesheet)"
echo "  - _sass/base/_reset.scss (CSS reset)"
echo "  - _sass/base/_typography.scss (typography system)"
echo "  - _sass/layout/_container.scss (container utilities)"
echo "  - _sass/layout/_grid.scss (grid system - updated)"
echo "  - _sass/components/_buttons.scss (button components)"
echo "  - _sass/components/_cards.scss (card components)"
echo "  - _sass/components/_forms.scss (form elements)"
echo "  - _sass/components/_header.scss (header & navigation)"
echo "  - _sass/components/_footer.scss (footer)"
echo "  - _sass/components/_hero.scss (hero sections)"
echo "  - _sass/utilities/_helpers.scss (utility classes - updated)"
echo ""
echo "📝 Updated files:"
echo "  - package.json (updated npm scripts)"
echo "  - assets/css/main-build.scss → main.scss (renamed)"
echo "  - Documentation files"
echo ""
echo "🗑️  Files to delete:"
echo "  - assets/css/main-build.scss (duplicate)"
echo "  - src/scss/ (old unused directory)"
echo "  - src/assets/ (old unused directory)"
echo ""
echo "To stage all new/modified files, run:"
echo "  git add ."
echo ""
echo "To commit, run:"
echo "  git commit -m 'Refactor: Modern theme architecture with HTML5/CSS3'"
echo ""
echo "Or stage selectively:"
echo "  git add _sass/"
echo "  git add assets/css/main.scss"
echo "  git add package.json"
echo "  git add *.md"
